# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/xxv_ethernet_0_example_top.xdc

# TCL: /home/koutarou/Desktop/mqtt/code/syn/axis_async_fifo.tcl

# TCL: /home/koutarou/Desktop/mqtt/code/syn/eth_mac_fifo.tcl

# TCL: /home/koutarou/Desktop/mqtt/code/syn/sync_reset.tcl

# IP: ip/topic_blk_mem_gen_0/topic_blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==topic_blk_mem_gen_0 || ORIG_REF_NAME==topic_blk_mem_gen_0} -quiet] -quiet

# IP: ip/sub_blk_mem_gen_0/sub_blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_blk_mem_gen_0 || ORIG_REF_NAME==sub_blk_mem_gen_0} -quiet] -quiet

# IP: ip/xxv_ethernet_0/xxv_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xxv_ethernet_0 || ORIG_REF_NAME==xxv_ethernet_0} -quiet] -quiet

# IP: ip/xxv_ethernet_0/ip_0/xxv_ethernet_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt || ORIG_REF_NAME==xxv_ethernet_0_gt} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi32regs_0_0/design_1_axi32regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi32regs_0_0 || ORIG_REF_NAME==design_1_axi32regs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_sync_0_0/design_1_clk_sync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_sync_0_0 || ORIG_REF_NAME==design_1_clk_sync_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: ip/xxv_ethernet_0/synth/xxv_ethernet_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0 || ORIG_REF_NAME==xxv_ethernet_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/xxv_ethernet_0/synth/xxv_ethernet_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0 || ORIG_REF_NAME==xxv_ethernet_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/xxv_ethernet_0/synth/xxv_ethernet_0_exceptions.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0 || ORIG_REF_NAME==xxv_ethernet_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/xxv_ethernet_0/synth/xxv_ethernet_0_ooc.xdc

# XDC: ip/xxv_ethernet_0/ip_0/synth/xxv_ethernet_0_gt_ooc.xdc

# XDC: ip/xxv_ethernet_0/ip_0/synth/xxv_ethernet_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt || ORIG_REF_NAME==xxv_ethernet_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
