# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 7
create_project -in_memory -part xczu19eg-ffvc1760-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.cache/wt [current_project]
set_property parent.project_path /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/koutarou/Desktop/mqtt/code/rtl/simple_ht/CRC32_D32.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_parser/count_array.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_parser/get_char_hot_array.sv
  /home/koutarou/Desktop/mqtt/code/rtl/lookup_engine/lookup_engine_pkg.sv
  /home/koutarou/Desktop/mqtt/code/rtl/lookup_engine/lookup_engine.sv
  /home/koutarou/Desktop/mqtt/code/rtl/lookup_engine/lookup_engine_execute.sv
  /home/koutarou/Desktop/mqtt/code/rtl/lookup_engine/lookup_engine_search_sub.sv
  /home/koutarou/Desktop/mqtt/code/rtl/lookup_engine/lookup_engine_search_topic.sv
  /home/koutarou/Desktop/mqtt/code/rtl/msg_fifo/msg_fifo_pkg.sv
  /home/koutarou/Desktop/mqtt/code/rtl/mqtt_top/mqtt_top.sv
  /home/koutarou/Desktop/mqtt/code/rtl/msg_fifo/msg_fifo.sv
  /home/koutarou/Desktop/mqtt/code/rtl/simple_ht/simple_dual_port_bram.sv
  /home/koutarou/Desktop/mqtt/code/rtl/simple_ht/simple_ht.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_parser/udp_mqtt_parser.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_parser/udp_mqtt_parser_dispatcher.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_parser/udp_mqtt_parser_duplicator.sv
  /home/koutarou/Desktop/mqtt/code/rtl/udp_mqtt_pkt_gen/udp_mqtt_pkt_gen.sv
}
read_verilog -library xil_defaultlib {
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/arbiter.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/arp.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/arp_cache.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/arp_eth_rx.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/arp_eth_tx.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_adapter.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_async_fifo.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_async_fifo_adapter.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_fifo.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_xgmii_rx_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/axis_xgmii_tx_64.v
  /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/eth_arb_mux.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/eth_axis_rx.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/eth_axis_tx.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/eth_mac_10g.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/eth_mac_10g_fifo.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/fpga_core.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ip_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ip_arb_mux.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ip_complete_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ip_eth_rx_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ip_eth_tx_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/lfsr.v
  /home/koutarou/Desktop/mqtt/code/rtl/msg_fifo/msg_axis_fifo.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/priority_encoder.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ptp_clock_cdc.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ptp_tag_insert.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/ptp_ts_extract.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/sync_reset.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/udp_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/udp_checksum_gen_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/udp_complete_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/udp_ip_rx_64.v
  /home/koutarou/Desktop/mqtt/code/rtl/network_stack/udp_ip_tx_64.v
  /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/imports/imports/xxv_ethernet_0_exdes.v
}
read_ip -quiet /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/topic_blk_mem_gen_0/topic_blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/topic_blk_mem_gen_0/topic_blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/sub_blk_mem_gen_0/sub_blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/sub_blk_mem_gen_0/sub_blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/xxv_ethernet_0.xci
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_exceptions.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/ip_0/synth/xxv_ethernet_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/ip/xxv_ethernet_0/ip_0/synth/xxv_ethernet_0_gt.xdc]

add_files /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/constrs_1/imports/imports/xxv_ethernet_0_example_top.xdc
set_property used_in_implementation false [get_files /home/koutarou/Desktop/mqtt/mqtt_mcube10fpga/MKUBOS-10GbE/MKUBOS-10GbE.srcs/constrs_1/imports/imports/xxv_ethernet_0_example_top.xdc]

read_xdc -unmanaged /home/koutarou/Desktop/mqtt/code/syn/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/koutarou/Desktop/mqtt/code/syn/axis_async_fifo.tcl]

read_xdc -unmanaged /home/koutarou/Desktop/mqtt/code/syn/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files /home/koutarou/Desktop/mqtt/code/syn/eth_mac_fifo.tcl]

read_xdc -unmanaged /home/koutarou/Desktop/mqtt/code/syn/sync_reset.tcl
set_property used_in_implementation false [get_files /home/koutarou/Desktop/mqtt/code/syn/sync_reset.tcl]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xxv_ethernet_0_exdes -part xczu19eg-ffvc1760-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xxv_ethernet_0_exdes.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xxv_ethernet_0_exdes_utilization_synth.rpt -pb xxv_ethernet_0_exdes_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
