-- Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2019.1 (lin64) Build 2552052 Fri May 24 14:47:09 MDT 2019
-- Date        : Tue Dec  1 15:56:42 2020
-- Host        : hien running 64-bit Ubuntu 18.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ xxv_ethernet_0_stub.vhdl
-- Design      : xxv_ethernet_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu19eg-ffvc1760-2-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    gt_rxp_in_0 : in STD_LOGIC;
    gt_rxn_in_0 : in STD_LOGIC;
    gt_txp_out_0 : out STD_LOGIC;
    gt_txn_out_0 : out STD_LOGIC;
    gt_rxp_in_1 : in STD_LOGIC;
    gt_rxn_in_1 : in STD_LOGIC;
    gt_txp_out_1 : out STD_LOGIC;
    gt_txn_out_1 : out STD_LOGIC;
    gt_rxp_in_2 : in STD_LOGIC;
    gt_rxn_in_2 : in STD_LOGIC;
    gt_txp_out_2 : out STD_LOGIC;
    gt_txn_out_2 : out STD_LOGIC;
    gt_rxp_in_3 : in STD_LOGIC;
    gt_rxn_in_3 : in STD_LOGIC;
    gt_txp_out_3 : out STD_LOGIC;
    gt_txn_out_3 : out STD_LOGIC;
    tx_clk_out_0 : out STD_LOGIC;
    rx_core_clk_0 : in STD_LOGIC;
    rx_clk_out_0 : out STD_LOGIC;
    gt_loopback_in_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rx_reset_0 : in STD_LOGIC;
    user_rx_reset_0 : out STD_LOGIC;
    rxrecclkout_0 : out STD_LOGIC;
    rx_axis_tvalid_0 : out STD_LOGIC;
    rx_axis_tdata_0 : out STD_LOGIC_VECTOR ( 63 downto 0 );
    rx_axis_tlast_0 : out STD_LOGIC;
    rx_axis_tkeep_0 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_axis_tuser_0 : out STD_LOGIC;
    rx_preambleout_0 : out STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_rx_test_pattern_0 : in STD_LOGIC;
    ctl_rx_test_pattern_enable_0 : in STD_LOGIC;
    ctl_rx_data_pattern_select_0 : in STD_LOGIC;
    ctl_rx_enable_0 : in STD_LOGIC;
    ctl_rx_delete_fcs_0 : in STD_LOGIC;
    ctl_rx_ignore_fcs_0 : in STD_LOGIC;
    ctl_rx_max_packet_len_0 : in STD_LOGIC_VECTOR ( 14 downto 0 );
    ctl_rx_min_packet_len_0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ctl_rx_custom_preamble_enable_0 : in STD_LOGIC;
    ctl_rx_check_sfd_0 : in STD_LOGIC;
    ctl_rx_check_preamble_0 : in STD_LOGIC;
    ctl_rx_process_lfi_0 : in STD_LOGIC;
    ctl_rx_force_resync_0 : in STD_LOGIC;
    stat_rx_block_lock_0 : out STD_LOGIC;
    stat_rx_framing_err_valid_0 : out STD_LOGIC;
    stat_rx_framing_err_0 : out STD_LOGIC;
    stat_rx_hi_ber_0 : out STD_LOGIC;
    stat_rx_valid_ctrl_code_0 : out STD_LOGIC;
    stat_rx_bad_code_0 : out STD_LOGIC;
    stat_rx_total_packets_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_total_good_packets_0 : out STD_LOGIC;
    stat_rx_total_bytes_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_rx_total_good_bytes_0 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_rx_packet_small_0 : out STD_LOGIC;
    stat_rx_jabber_0 : out STD_LOGIC;
    stat_rx_packet_large_0 : out STD_LOGIC;
    stat_rx_oversize_0 : out STD_LOGIC;
    stat_rx_undersize_0 : out STD_LOGIC;
    stat_rx_toolong_0 : out STD_LOGIC;
    stat_rx_fragment_0 : out STD_LOGIC;
    stat_rx_packet_64_bytes_0 : out STD_LOGIC;
    stat_rx_packet_65_127_bytes_0 : out STD_LOGIC;
    stat_rx_packet_128_255_bytes_0 : out STD_LOGIC;
    stat_rx_packet_256_511_bytes_0 : out STD_LOGIC;
    stat_rx_packet_512_1023_bytes_0 : out STD_LOGIC;
    stat_rx_packet_1024_1518_bytes_0 : out STD_LOGIC;
    stat_rx_packet_1519_1522_bytes_0 : out STD_LOGIC;
    stat_rx_packet_1523_1548_bytes_0 : out STD_LOGIC;
    stat_rx_bad_fcs_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_bad_fcs_0 : out STD_LOGIC;
    stat_rx_stomped_fcs_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_1549_2047_bytes_0 : out STD_LOGIC;
    stat_rx_packet_2048_4095_bytes_0 : out STD_LOGIC;
    stat_rx_packet_4096_8191_bytes_0 : out STD_LOGIC;
    stat_rx_packet_8192_9215_bytes_0 : out STD_LOGIC;
    stat_rx_unicast_0 : out STD_LOGIC;
    stat_rx_multicast_0 : out STD_LOGIC;
    stat_rx_broadcast_0 : out STD_LOGIC;
    stat_rx_vlan_0 : out STD_LOGIC;
    stat_rx_inrangeerr_0 : out STD_LOGIC;
    stat_rx_bad_preamble_0 : out STD_LOGIC;
    stat_rx_bad_sfd_0 : out STD_LOGIC;
    stat_rx_got_signal_os_0 : out STD_LOGIC;
    stat_rx_test_pattern_mismatch_0 : out STD_LOGIC;
    stat_rx_truncated_0 : out STD_LOGIC;
    stat_rx_local_fault_0 : out STD_LOGIC;
    stat_rx_remote_fault_0 : out STD_LOGIC;
    stat_rx_internal_local_fault_0 : out STD_LOGIC;
    stat_rx_received_local_fault_0 : out STD_LOGIC;
    stat_rx_status_0 : out STD_LOGIC;
    tx_reset_0 : in STD_LOGIC;
    user_tx_reset_0 : out STD_LOGIC;
    tx_axis_tready_0 : out STD_LOGIC;
    tx_axis_tvalid_0 : in STD_LOGIC;
    tx_axis_tdata_0 : in STD_LOGIC_VECTOR ( 63 downto 0 );
    tx_axis_tlast_0 : in STD_LOGIC;
    tx_axis_tkeep_0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    tx_axis_tuser_0 : in STD_LOGIC;
    tx_unfout_0 : out STD_LOGIC;
    tx_preamblein_0 : in STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_tx_test_pattern_0 : in STD_LOGIC;
    ctl_tx_test_pattern_enable_0 : in STD_LOGIC;
    ctl_tx_test_pattern_select_0 : in STD_LOGIC;
    ctl_tx_data_pattern_select_0 : in STD_LOGIC;
    ctl_tx_test_pattern_seed_a_0 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_test_pattern_seed_b_0 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_enable_0 : in STD_LOGIC;
    ctl_tx_fcs_ins_enable_0 : in STD_LOGIC;
    ctl_tx_ipg_value_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ctl_tx_send_lfi_0 : in STD_LOGIC;
    ctl_tx_send_rfi_0 : in STD_LOGIC;
    ctl_tx_send_idle_0 : in STD_LOGIC;
    ctl_tx_custom_preamble_enable_0 : in STD_LOGIC;
    ctl_tx_ignore_fcs_0 : in STD_LOGIC;
    stat_tx_total_packets_0 : out STD_LOGIC;
    stat_tx_total_bytes_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_tx_total_good_packets_0 : out STD_LOGIC;
    stat_tx_total_good_bytes_0 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_tx_packet_64_bytes_0 : out STD_LOGIC;
    stat_tx_packet_65_127_bytes_0 : out STD_LOGIC;
    stat_tx_packet_128_255_bytes_0 : out STD_LOGIC;
    stat_tx_packet_256_511_bytes_0 : out STD_LOGIC;
    stat_tx_packet_512_1023_bytes_0 : out STD_LOGIC;
    stat_tx_packet_1024_1518_bytes_0 : out STD_LOGIC;
    stat_tx_packet_1519_1522_bytes_0 : out STD_LOGIC;
    stat_tx_packet_1523_1548_bytes_0 : out STD_LOGIC;
    stat_tx_packet_small_0 : out STD_LOGIC;
    stat_tx_packet_large_0 : out STD_LOGIC;
    stat_tx_packet_1549_2047_bytes_0 : out STD_LOGIC;
    stat_tx_packet_2048_4095_bytes_0 : out STD_LOGIC;
    stat_tx_packet_4096_8191_bytes_0 : out STD_LOGIC;
    stat_tx_packet_8192_9215_bytes_0 : out STD_LOGIC;
    stat_tx_unicast_0 : out STD_LOGIC;
    stat_tx_multicast_0 : out STD_LOGIC;
    stat_tx_broadcast_0 : out STD_LOGIC;
    stat_tx_vlan_0 : out STD_LOGIC;
    stat_tx_bad_fcs_0 : out STD_LOGIC;
    stat_tx_frame_error_0 : out STD_LOGIC;
    stat_tx_local_fault_0 : out STD_LOGIC;
    gt_dmonitorout_0 : out STD_LOGIC_VECTOR ( 16 downto 0 );
    gt_eyescandataerror_0 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescanreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescantrigger_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_pcsrsvdin_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_rxbufreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxbufstatus_0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxcdrhold_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxcommadeten_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfeagchold_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfelpmreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlatclk_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlpmen_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpcsreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpmareset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpolarity_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbscntreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbserr_0 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbssel_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_rxrate_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxslide_in_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxstartofseq_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txbufstatus_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txinhibit_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txlatclk_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txmaincursor_0 : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt_txpcsreset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpmareset_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpolarity_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpostcursor_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txprbsforceerr_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txprbssel_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_txprecursor_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txdiffctrl_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_drpdo_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drprdy_0 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpen_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpwe_0 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpaddr_0 : in STD_LOGIC_VECTOR ( 9 downto 0 );
    gt_drpdi_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drpclk_0 : in STD_LOGIC;
    gtwiz_reset_tx_datapath_0 : in STD_LOGIC;
    gtwiz_reset_rx_datapath_0 : in STD_LOGIC;
    gtpowergood_out_0 : out STD_LOGIC;
    txoutclksel_in_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rxoutclksel_in_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    tx_clk_out_1 : out STD_LOGIC;
    rx_core_clk_1 : in STD_LOGIC;
    rx_clk_out_1 : out STD_LOGIC;
    gt_loopback_in_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rx_reset_1 : in STD_LOGIC;
    user_rx_reset_1 : out STD_LOGIC;
    rxrecclkout_1 : out STD_LOGIC;
    rx_axis_tvalid_1 : out STD_LOGIC;
    rx_axis_tdata_1 : out STD_LOGIC_VECTOR ( 63 downto 0 );
    rx_axis_tlast_1 : out STD_LOGIC;
    rx_axis_tkeep_1 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_axis_tuser_1 : out STD_LOGIC;
    rx_preambleout_1 : out STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_rx_test_pattern_1 : in STD_LOGIC;
    ctl_rx_test_pattern_enable_1 : in STD_LOGIC;
    ctl_rx_data_pattern_select_1 : in STD_LOGIC;
    ctl_rx_enable_1 : in STD_LOGIC;
    ctl_rx_delete_fcs_1 : in STD_LOGIC;
    ctl_rx_ignore_fcs_1 : in STD_LOGIC;
    ctl_rx_max_packet_len_1 : in STD_LOGIC_VECTOR ( 14 downto 0 );
    ctl_rx_min_packet_len_1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ctl_rx_custom_preamble_enable_1 : in STD_LOGIC;
    ctl_rx_check_sfd_1 : in STD_LOGIC;
    ctl_rx_check_preamble_1 : in STD_LOGIC;
    ctl_rx_process_lfi_1 : in STD_LOGIC;
    ctl_rx_force_resync_1 : in STD_LOGIC;
    stat_rx_block_lock_1 : out STD_LOGIC;
    stat_rx_framing_err_valid_1 : out STD_LOGIC;
    stat_rx_framing_err_1 : out STD_LOGIC;
    stat_rx_hi_ber_1 : out STD_LOGIC;
    stat_rx_valid_ctrl_code_1 : out STD_LOGIC;
    stat_rx_bad_code_1 : out STD_LOGIC;
    stat_rx_total_packets_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_total_good_packets_1 : out STD_LOGIC;
    stat_rx_total_bytes_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_rx_total_good_bytes_1 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_rx_packet_small_1 : out STD_LOGIC;
    stat_rx_jabber_1 : out STD_LOGIC;
    stat_rx_packet_large_1 : out STD_LOGIC;
    stat_rx_oversize_1 : out STD_LOGIC;
    stat_rx_undersize_1 : out STD_LOGIC;
    stat_rx_toolong_1 : out STD_LOGIC;
    stat_rx_fragment_1 : out STD_LOGIC;
    stat_rx_packet_64_bytes_1 : out STD_LOGIC;
    stat_rx_packet_65_127_bytes_1 : out STD_LOGIC;
    stat_rx_packet_128_255_bytes_1 : out STD_LOGIC;
    stat_rx_packet_256_511_bytes_1 : out STD_LOGIC;
    stat_rx_packet_512_1023_bytes_1 : out STD_LOGIC;
    stat_rx_packet_1024_1518_bytes_1 : out STD_LOGIC;
    stat_rx_packet_1519_1522_bytes_1 : out STD_LOGIC;
    stat_rx_packet_1523_1548_bytes_1 : out STD_LOGIC;
    stat_rx_bad_fcs_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_bad_fcs_1 : out STD_LOGIC;
    stat_rx_stomped_fcs_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_1549_2047_bytes_1 : out STD_LOGIC;
    stat_rx_packet_2048_4095_bytes_1 : out STD_LOGIC;
    stat_rx_packet_4096_8191_bytes_1 : out STD_LOGIC;
    stat_rx_packet_8192_9215_bytes_1 : out STD_LOGIC;
    stat_rx_unicast_1 : out STD_LOGIC;
    stat_rx_multicast_1 : out STD_LOGIC;
    stat_rx_broadcast_1 : out STD_LOGIC;
    stat_rx_vlan_1 : out STD_LOGIC;
    stat_rx_inrangeerr_1 : out STD_LOGIC;
    stat_rx_bad_preamble_1 : out STD_LOGIC;
    stat_rx_bad_sfd_1 : out STD_LOGIC;
    stat_rx_got_signal_os_1 : out STD_LOGIC;
    stat_rx_test_pattern_mismatch_1 : out STD_LOGIC;
    stat_rx_truncated_1 : out STD_LOGIC;
    stat_rx_local_fault_1 : out STD_LOGIC;
    stat_rx_remote_fault_1 : out STD_LOGIC;
    stat_rx_internal_local_fault_1 : out STD_LOGIC;
    stat_rx_received_local_fault_1 : out STD_LOGIC;
    stat_rx_status_1 : out STD_LOGIC;
    tx_reset_1 : in STD_LOGIC;
    user_tx_reset_1 : out STD_LOGIC;
    tx_axis_tready_1 : out STD_LOGIC;
    tx_axis_tvalid_1 : in STD_LOGIC;
    tx_axis_tdata_1 : in STD_LOGIC_VECTOR ( 63 downto 0 );
    tx_axis_tlast_1 : in STD_LOGIC;
    tx_axis_tkeep_1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    tx_axis_tuser_1 : in STD_LOGIC;
    tx_unfout_1 : out STD_LOGIC;
    tx_preamblein_1 : in STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_tx_test_pattern_1 : in STD_LOGIC;
    ctl_tx_test_pattern_enable_1 : in STD_LOGIC;
    ctl_tx_test_pattern_select_1 : in STD_LOGIC;
    ctl_tx_data_pattern_select_1 : in STD_LOGIC;
    ctl_tx_test_pattern_seed_a_1 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_test_pattern_seed_b_1 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_enable_1 : in STD_LOGIC;
    ctl_tx_fcs_ins_enable_1 : in STD_LOGIC;
    ctl_tx_ipg_value_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ctl_tx_send_lfi_1 : in STD_LOGIC;
    ctl_tx_send_rfi_1 : in STD_LOGIC;
    ctl_tx_send_idle_1 : in STD_LOGIC;
    ctl_tx_custom_preamble_enable_1 : in STD_LOGIC;
    ctl_tx_ignore_fcs_1 : in STD_LOGIC;
    stat_tx_total_packets_1 : out STD_LOGIC;
    stat_tx_total_bytes_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_tx_total_good_packets_1 : out STD_LOGIC;
    stat_tx_total_good_bytes_1 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_tx_packet_64_bytes_1 : out STD_LOGIC;
    stat_tx_packet_65_127_bytes_1 : out STD_LOGIC;
    stat_tx_packet_128_255_bytes_1 : out STD_LOGIC;
    stat_tx_packet_256_511_bytes_1 : out STD_LOGIC;
    stat_tx_packet_512_1023_bytes_1 : out STD_LOGIC;
    stat_tx_packet_1024_1518_bytes_1 : out STD_LOGIC;
    stat_tx_packet_1519_1522_bytes_1 : out STD_LOGIC;
    stat_tx_packet_1523_1548_bytes_1 : out STD_LOGIC;
    stat_tx_packet_small_1 : out STD_LOGIC;
    stat_tx_packet_large_1 : out STD_LOGIC;
    stat_tx_packet_1549_2047_bytes_1 : out STD_LOGIC;
    stat_tx_packet_2048_4095_bytes_1 : out STD_LOGIC;
    stat_tx_packet_4096_8191_bytes_1 : out STD_LOGIC;
    stat_tx_packet_8192_9215_bytes_1 : out STD_LOGIC;
    stat_tx_unicast_1 : out STD_LOGIC;
    stat_tx_multicast_1 : out STD_LOGIC;
    stat_tx_broadcast_1 : out STD_LOGIC;
    stat_tx_vlan_1 : out STD_LOGIC;
    stat_tx_bad_fcs_1 : out STD_LOGIC;
    stat_tx_frame_error_1 : out STD_LOGIC;
    stat_tx_local_fault_1 : out STD_LOGIC;
    gt_dmonitorout_1 : out STD_LOGIC_VECTOR ( 16 downto 0 );
    gt_eyescandataerror_1 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescanreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescantrigger_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_pcsrsvdin_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_rxbufreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxbufstatus_1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxcdrhold_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxcommadeten_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfeagchold_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfelpmreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlatclk_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlpmen_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpcsreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpmareset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpolarity_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbscntreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbserr_1 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbssel_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_rxrate_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxslide_in_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxstartofseq_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txbufstatus_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txinhibit_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txlatclk_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txmaincursor_1 : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt_txpcsreset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpmareset_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpolarity_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpostcursor_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txprbsforceerr_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txprbssel_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_txprecursor_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txdiffctrl_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_drpdo_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drprdy_1 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpen_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpwe_1 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpaddr_1 : in STD_LOGIC_VECTOR ( 9 downto 0 );
    gt_drpdi_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drpclk_1 : in STD_LOGIC;
    gtwiz_reset_tx_datapath_1 : in STD_LOGIC;
    gtwiz_reset_rx_datapath_1 : in STD_LOGIC;
    gtpowergood_out_1 : out STD_LOGIC;
    txoutclksel_in_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rxoutclksel_in_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    tx_clk_out_2 : out STD_LOGIC;
    rx_core_clk_2 : in STD_LOGIC;
    rx_clk_out_2 : out STD_LOGIC;
    gt_loopback_in_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rx_reset_2 : in STD_LOGIC;
    user_rx_reset_2 : out STD_LOGIC;
    rxrecclkout_2 : out STD_LOGIC;
    rx_axis_tvalid_2 : out STD_LOGIC;
    rx_axis_tdata_2 : out STD_LOGIC_VECTOR ( 63 downto 0 );
    rx_axis_tlast_2 : out STD_LOGIC;
    rx_axis_tkeep_2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_axis_tuser_2 : out STD_LOGIC;
    rx_preambleout_2 : out STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_rx_test_pattern_2 : in STD_LOGIC;
    ctl_rx_test_pattern_enable_2 : in STD_LOGIC;
    ctl_rx_data_pattern_select_2 : in STD_LOGIC;
    ctl_rx_enable_2 : in STD_LOGIC;
    ctl_rx_delete_fcs_2 : in STD_LOGIC;
    ctl_rx_ignore_fcs_2 : in STD_LOGIC;
    ctl_rx_max_packet_len_2 : in STD_LOGIC_VECTOR ( 14 downto 0 );
    ctl_rx_min_packet_len_2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ctl_rx_custom_preamble_enable_2 : in STD_LOGIC;
    ctl_rx_check_sfd_2 : in STD_LOGIC;
    ctl_rx_check_preamble_2 : in STD_LOGIC;
    ctl_rx_process_lfi_2 : in STD_LOGIC;
    ctl_rx_force_resync_2 : in STD_LOGIC;
    stat_rx_block_lock_2 : out STD_LOGIC;
    stat_rx_framing_err_valid_2 : out STD_LOGIC;
    stat_rx_framing_err_2 : out STD_LOGIC;
    stat_rx_hi_ber_2 : out STD_LOGIC;
    stat_rx_valid_ctrl_code_2 : out STD_LOGIC;
    stat_rx_bad_code_2 : out STD_LOGIC;
    stat_rx_total_packets_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_total_good_packets_2 : out STD_LOGIC;
    stat_rx_total_bytes_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_rx_total_good_bytes_2 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_rx_packet_small_2 : out STD_LOGIC;
    stat_rx_jabber_2 : out STD_LOGIC;
    stat_rx_packet_large_2 : out STD_LOGIC;
    stat_rx_oversize_2 : out STD_LOGIC;
    stat_rx_undersize_2 : out STD_LOGIC;
    stat_rx_toolong_2 : out STD_LOGIC;
    stat_rx_fragment_2 : out STD_LOGIC;
    stat_rx_packet_64_bytes_2 : out STD_LOGIC;
    stat_rx_packet_65_127_bytes_2 : out STD_LOGIC;
    stat_rx_packet_128_255_bytes_2 : out STD_LOGIC;
    stat_rx_packet_256_511_bytes_2 : out STD_LOGIC;
    stat_rx_packet_512_1023_bytes_2 : out STD_LOGIC;
    stat_rx_packet_1024_1518_bytes_2 : out STD_LOGIC;
    stat_rx_packet_1519_1522_bytes_2 : out STD_LOGIC;
    stat_rx_packet_1523_1548_bytes_2 : out STD_LOGIC;
    stat_rx_bad_fcs_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_bad_fcs_2 : out STD_LOGIC;
    stat_rx_stomped_fcs_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_1549_2047_bytes_2 : out STD_LOGIC;
    stat_rx_packet_2048_4095_bytes_2 : out STD_LOGIC;
    stat_rx_packet_4096_8191_bytes_2 : out STD_LOGIC;
    stat_rx_packet_8192_9215_bytes_2 : out STD_LOGIC;
    stat_rx_unicast_2 : out STD_LOGIC;
    stat_rx_multicast_2 : out STD_LOGIC;
    stat_rx_broadcast_2 : out STD_LOGIC;
    stat_rx_vlan_2 : out STD_LOGIC;
    stat_rx_inrangeerr_2 : out STD_LOGIC;
    stat_rx_bad_preamble_2 : out STD_LOGIC;
    stat_rx_bad_sfd_2 : out STD_LOGIC;
    stat_rx_got_signal_os_2 : out STD_LOGIC;
    stat_rx_test_pattern_mismatch_2 : out STD_LOGIC;
    stat_rx_truncated_2 : out STD_LOGIC;
    stat_rx_local_fault_2 : out STD_LOGIC;
    stat_rx_remote_fault_2 : out STD_LOGIC;
    stat_rx_internal_local_fault_2 : out STD_LOGIC;
    stat_rx_received_local_fault_2 : out STD_LOGIC;
    stat_rx_status_2 : out STD_LOGIC;
    tx_reset_2 : in STD_LOGIC;
    user_tx_reset_2 : out STD_LOGIC;
    tx_axis_tready_2 : out STD_LOGIC;
    tx_axis_tvalid_2 : in STD_LOGIC;
    tx_axis_tdata_2 : in STD_LOGIC_VECTOR ( 63 downto 0 );
    tx_axis_tlast_2 : in STD_LOGIC;
    tx_axis_tkeep_2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    tx_axis_tuser_2 : in STD_LOGIC;
    tx_unfout_2 : out STD_LOGIC;
    tx_preamblein_2 : in STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_tx_test_pattern_2 : in STD_LOGIC;
    ctl_tx_test_pattern_enable_2 : in STD_LOGIC;
    ctl_tx_test_pattern_select_2 : in STD_LOGIC;
    ctl_tx_data_pattern_select_2 : in STD_LOGIC;
    ctl_tx_test_pattern_seed_a_2 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_test_pattern_seed_b_2 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_enable_2 : in STD_LOGIC;
    ctl_tx_fcs_ins_enable_2 : in STD_LOGIC;
    ctl_tx_ipg_value_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ctl_tx_send_lfi_2 : in STD_LOGIC;
    ctl_tx_send_rfi_2 : in STD_LOGIC;
    ctl_tx_send_idle_2 : in STD_LOGIC;
    ctl_tx_custom_preamble_enable_2 : in STD_LOGIC;
    ctl_tx_ignore_fcs_2 : in STD_LOGIC;
    stat_tx_total_packets_2 : out STD_LOGIC;
    stat_tx_total_bytes_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_tx_total_good_packets_2 : out STD_LOGIC;
    stat_tx_total_good_bytes_2 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_tx_packet_64_bytes_2 : out STD_LOGIC;
    stat_tx_packet_65_127_bytes_2 : out STD_LOGIC;
    stat_tx_packet_128_255_bytes_2 : out STD_LOGIC;
    stat_tx_packet_256_511_bytes_2 : out STD_LOGIC;
    stat_tx_packet_512_1023_bytes_2 : out STD_LOGIC;
    stat_tx_packet_1024_1518_bytes_2 : out STD_LOGIC;
    stat_tx_packet_1519_1522_bytes_2 : out STD_LOGIC;
    stat_tx_packet_1523_1548_bytes_2 : out STD_LOGIC;
    stat_tx_packet_small_2 : out STD_LOGIC;
    stat_tx_packet_large_2 : out STD_LOGIC;
    stat_tx_packet_1549_2047_bytes_2 : out STD_LOGIC;
    stat_tx_packet_2048_4095_bytes_2 : out STD_LOGIC;
    stat_tx_packet_4096_8191_bytes_2 : out STD_LOGIC;
    stat_tx_packet_8192_9215_bytes_2 : out STD_LOGIC;
    stat_tx_unicast_2 : out STD_LOGIC;
    stat_tx_multicast_2 : out STD_LOGIC;
    stat_tx_broadcast_2 : out STD_LOGIC;
    stat_tx_vlan_2 : out STD_LOGIC;
    stat_tx_bad_fcs_2 : out STD_LOGIC;
    stat_tx_frame_error_2 : out STD_LOGIC;
    stat_tx_local_fault_2 : out STD_LOGIC;
    gt_dmonitorout_2 : out STD_LOGIC_VECTOR ( 16 downto 0 );
    gt_eyescandataerror_2 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescanreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescantrigger_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_pcsrsvdin_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_rxbufreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxbufstatus_2 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxcdrhold_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxcommadeten_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfeagchold_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfelpmreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlatclk_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlpmen_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpcsreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpmareset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpolarity_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbscntreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbserr_2 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbssel_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_rxrate_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxslide_in_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxstartofseq_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txbufstatus_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txinhibit_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txlatclk_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txmaincursor_2 : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt_txpcsreset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpmareset_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpolarity_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpostcursor_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txprbsforceerr_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txprbssel_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_txprecursor_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txdiffctrl_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_drpdo_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drprdy_2 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpen_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpwe_2 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpaddr_2 : in STD_LOGIC_VECTOR ( 9 downto 0 );
    gt_drpdi_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drpclk_2 : in STD_LOGIC;
    gtwiz_reset_tx_datapath_2 : in STD_LOGIC;
    gtwiz_reset_rx_datapath_2 : in STD_LOGIC;
    gtpowergood_out_2 : out STD_LOGIC;
    txoutclksel_in_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rxoutclksel_in_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    tx_clk_out_3 : out STD_LOGIC;
    rx_core_clk_3 : in STD_LOGIC;
    rx_clk_out_3 : out STD_LOGIC;
    gt_loopback_in_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rx_reset_3 : in STD_LOGIC;
    user_rx_reset_3 : out STD_LOGIC;
    rxrecclkout_3 : out STD_LOGIC;
    rx_axis_tvalid_3 : out STD_LOGIC;
    rx_axis_tdata_3 : out STD_LOGIC_VECTOR ( 63 downto 0 );
    rx_axis_tlast_3 : out STD_LOGIC;
    rx_axis_tkeep_3 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_axis_tuser_3 : out STD_LOGIC;
    rx_preambleout_3 : out STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_rx_test_pattern_3 : in STD_LOGIC;
    ctl_rx_test_pattern_enable_3 : in STD_LOGIC;
    ctl_rx_data_pattern_select_3 : in STD_LOGIC;
    ctl_rx_enable_3 : in STD_LOGIC;
    ctl_rx_delete_fcs_3 : in STD_LOGIC;
    ctl_rx_ignore_fcs_3 : in STD_LOGIC;
    ctl_rx_max_packet_len_3 : in STD_LOGIC_VECTOR ( 14 downto 0 );
    ctl_rx_min_packet_len_3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ctl_rx_custom_preamble_enable_3 : in STD_LOGIC;
    ctl_rx_check_sfd_3 : in STD_LOGIC;
    ctl_rx_check_preamble_3 : in STD_LOGIC;
    ctl_rx_process_lfi_3 : in STD_LOGIC;
    ctl_rx_force_resync_3 : in STD_LOGIC;
    stat_rx_block_lock_3 : out STD_LOGIC;
    stat_rx_framing_err_valid_3 : out STD_LOGIC;
    stat_rx_framing_err_3 : out STD_LOGIC;
    stat_rx_hi_ber_3 : out STD_LOGIC;
    stat_rx_valid_ctrl_code_3 : out STD_LOGIC;
    stat_rx_bad_code_3 : out STD_LOGIC;
    stat_rx_total_packets_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_total_good_packets_3 : out STD_LOGIC;
    stat_rx_total_bytes_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_rx_total_good_bytes_3 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_rx_packet_small_3 : out STD_LOGIC;
    stat_rx_jabber_3 : out STD_LOGIC;
    stat_rx_packet_large_3 : out STD_LOGIC;
    stat_rx_oversize_3 : out STD_LOGIC;
    stat_rx_undersize_3 : out STD_LOGIC;
    stat_rx_toolong_3 : out STD_LOGIC;
    stat_rx_fragment_3 : out STD_LOGIC;
    stat_rx_packet_64_bytes_3 : out STD_LOGIC;
    stat_rx_packet_65_127_bytes_3 : out STD_LOGIC;
    stat_rx_packet_128_255_bytes_3 : out STD_LOGIC;
    stat_rx_packet_256_511_bytes_3 : out STD_LOGIC;
    stat_rx_packet_512_1023_bytes_3 : out STD_LOGIC;
    stat_rx_packet_1024_1518_bytes_3 : out STD_LOGIC;
    stat_rx_packet_1519_1522_bytes_3 : out STD_LOGIC;
    stat_rx_packet_1523_1548_bytes_3 : out STD_LOGIC;
    stat_rx_bad_fcs_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_bad_fcs_3 : out STD_LOGIC;
    stat_rx_stomped_fcs_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    stat_rx_packet_1549_2047_bytes_3 : out STD_LOGIC;
    stat_rx_packet_2048_4095_bytes_3 : out STD_LOGIC;
    stat_rx_packet_4096_8191_bytes_3 : out STD_LOGIC;
    stat_rx_packet_8192_9215_bytes_3 : out STD_LOGIC;
    stat_rx_unicast_3 : out STD_LOGIC;
    stat_rx_multicast_3 : out STD_LOGIC;
    stat_rx_broadcast_3 : out STD_LOGIC;
    stat_rx_vlan_3 : out STD_LOGIC;
    stat_rx_inrangeerr_3 : out STD_LOGIC;
    stat_rx_bad_preamble_3 : out STD_LOGIC;
    stat_rx_bad_sfd_3 : out STD_LOGIC;
    stat_rx_got_signal_os_3 : out STD_LOGIC;
    stat_rx_test_pattern_mismatch_3 : out STD_LOGIC;
    stat_rx_truncated_3 : out STD_LOGIC;
    stat_rx_local_fault_3 : out STD_LOGIC;
    stat_rx_remote_fault_3 : out STD_LOGIC;
    stat_rx_internal_local_fault_3 : out STD_LOGIC;
    stat_rx_received_local_fault_3 : out STD_LOGIC;
    stat_rx_status_3 : out STD_LOGIC;
    tx_reset_3 : in STD_LOGIC;
    user_tx_reset_3 : out STD_LOGIC;
    tx_axis_tready_3 : out STD_LOGIC;
    tx_axis_tvalid_3 : in STD_LOGIC;
    tx_axis_tdata_3 : in STD_LOGIC_VECTOR ( 63 downto 0 );
    tx_axis_tlast_3 : in STD_LOGIC;
    tx_axis_tkeep_3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    tx_axis_tuser_3 : in STD_LOGIC;
    tx_unfout_3 : out STD_LOGIC;
    tx_preamblein_3 : in STD_LOGIC_VECTOR ( 55 downto 0 );
    ctl_tx_test_pattern_3 : in STD_LOGIC;
    ctl_tx_test_pattern_enable_3 : in STD_LOGIC;
    ctl_tx_test_pattern_select_3 : in STD_LOGIC;
    ctl_tx_data_pattern_select_3 : in STD_LOGIC;
    ctl_tx_test_pattern_seed_a_3 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_test_pattern_seed_b_3 : in STD_LOGIC_VECTOR ( 57 downto 0 );
    ctl_tx_enable_3 : in STD_LOGIC;
    ctl_tx_fcs_ins_enable_3 : in STD_LOGIC;
    ctl_tx_ipg_value_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ctl_tx_send_lfi_3 : in STD_LOGIC;
    ctl_tx_send_rfi_3 : in STD_LOGIC;
    ctl_tx_send_idle_3 : in STD_LOGIC;
    ctl_tx_custom_preamble_enable_3 : in STD_LOGIC;
    ctl_tx_ignore_fcs_3 : in STD_LOGIC;
    stat_tx_total_packets_3 : out STD_LOGIC;
    stat_tx_total_bytes_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    stat_tx_total_good_packets_3 : out STD_LOGIC;
    stat_tx_total_good_bytes_3 : out STD_LOGIC_VECTOR ( 13 downto 0 );
    stat_tx_packet_64_bytes_3 : out STD_LOGIC;
    stat_tx_packet_65_127_bytes_3 : out STD_LOGIC;
    stat_tx_packet_128_255_bytes_3 : out STD_LOGIC;
    stat_tx_packet_256_511_bytes_3 : out STD_LOGIC;
    stat_tx_packet_512_1023_bytes_3 : out STD_LOGIC;
    stat_tx_packet_1024_1518_bytes_3 : out STD_LOGIC;
    stat_tx_packet_1519_1522_bytes_3 : out STD_LOGIC;
    stat_tx_packet_1523_1548_bytes_3 : out STD_LOGIC;
    stat_tx_packet_small_3 : out STD_LOGIC;
    stat_tx_packet_large_3 : out STD_LOGIC;
    stat_tx_packet_1549_2047_bytes_3 : out STD_LOGIC;
    stat_tx_packet_2048_4095_bytes_3 : out STD_LOGIC;
    stat_tx_packet_4096_8191_bytes_3 : out STD_LOGIC;
    stat_tx_packet_8192_9215_bytes_3 : out STD_LOGIC;
    stat_tx_unicast_3 : out STD_LOGIC;
    stat_tx_multicast_3 : out STD_LOGIC;
    stat_tx_broadcast_3 : out STD_LOGIC;
    stat_tx_vlan_3 : out STD_LOGIC;
    stat_tx_bad_fcs_3 : out STD_LOGIC;
    stat_tx_frame_error_3 : out STD_LOGIC;
    stat_tx_local_fault_3 : out STD_LOGIC;
    gt_dmonitorout_3 : out STD_LOGIC_VECTOR ( 16 downto 0 );
    gt_eyescandataerror_3 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescanreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_eyescantrigger_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_pcsrsvdin_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_rxbufreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxbufstatus_3 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxcdrhold_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxcommadeten_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfeagchold_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxdfelpmreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlatclk_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxlpmen_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpcsreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpmareset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxpolarity_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbscntreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbserr_3 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxprbssel_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_rxrate_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_rxslide_in_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_rxstartofseq_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txbufstatus_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt_txinhibit_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txlatclk_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txmaincursor_3 : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt_txpcsreset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpmareset_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpolarity_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txpostcursor_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txprbsforceerr_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_txprbssel_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt_txprecursor_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_txdiffctrl_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt_drpdo_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drprdy_3 : out STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpen_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpwe_3 : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_drpaddr_3 : in STD_LOGIC_VECTOR ( 9 downto 0 );
    gt_drpdi_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt_drpclk_3 : in STD_LOGIC;
    gtwiz_reset_tx_datapath_3 : in STD_LOGIC;
    gtwiz_reset_rx_datapath_3 : in STD_LOGIC;
    gtpowergood_out_3 : out STD_LOGIC;
    txoutclksel_in_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    rxoutclksel_in_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt_refclk_p : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_refclk_n : in STD_LOGIC_VECTOR ( 0 to 0 );
    gt_refclk_out : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_reset : in STD_LOGIC;
    dclk : in STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "gt_rxp_in_0,gt_rxn_in_0,gt_txp_out_0,gt_txn_out_0,gt_rxp_in_1,gt_rxn_in_1,gt_txp_out_1,gt_txn_out_1,gt_rxp_in_2,gt_rxn_in_2,gt_txp_out_2,gt_txn_out_2,gt_rxp_in_3,gt_rxn_in_3,gt_txp_out_3,gt_txn_out_3,tx_clk_out_0,rx_core_clk_0,rx_clk_out_0,gt_loopback_in_0[2:0],rx_reset_0,user_rx_reset_0,rxrecclkout_0,rx_axis_tvalid_0,rx_axis_tdata_0[63:0],rx_axis_tlast_0,rx_axis_tkeep_0[7:0],rx_axis_tuser_0,rx_preambleout_0[55:0],ctl_rx_test_pattern_0,ctl_rx_test_pattern_enable_0,ctl_rx_data_pattern_select_0,ctl_rx_enable_0,ctl_rx_delete_fcs_0,ctl_rx_ignore_fcs_0,ctl_rx_max_packet_len_0[14:0],ctl_rx_min_packet_len_0[7:0],ctl_rx_custom_preamble_enable_0,ctl_rx_check_sfd_0,ctl_rx_check_preamble_0,ctl_rx_process_lfi_0,ctl_rx_force_resync_0,stat_rx_block_lock_0,stat_rx_framing_err_valid_0,stat_rx_framing_err_0,stat_rx_hi_ber_0,stat_rx_valid_ctrl_code_0,stat_rx_bad_code_0,stat_rx_total_packets_0[1:0],stat_rx_total_good_packets_0,stat_rx_total_bytes_0[3:0],stat_rx_total_good_bytes_0[13:0],stat_rx_packet_small_0,stat_rx_jabber_0,stat_rx_packet_large_0,stat_rx_oversize_0,stat_rx_undersize_0,stat_rx_toolong_0,stat_rx_fragment_0,stat_rx_packet_64_bytes_0,stat_rx_packet_65_127_bytes_0,stat_rx_packet_128_255_bytes_0,stat_rx_packet_256_511_bytes_0,stat_rx_packet_512_1023_bytes_0,stat_rx_packet_1024_1518_bytes_0,stat_rx_packet_1519_1522_bytes_0,stat_rx_packet_1523_1548_bytes_0,stat_rx_bad_fcs_0[1:0],stat_rx_packet_bad_fcs_0,stat_rx_stomped_fcs_0[1:0],stat_rx_packet_1549_2047_bytes_0,stat_rx_packet_2048_4095_bytes_0,stat_rx_packet_4096_8191_bytes_0,stat_rx_packet_8192_9215_bytes_0,stat_rx_unicast_0,stat_rx_multicast_0,stat_rx_broadcast_0,stat_rx_vlan_0,stat_rx_inrangeerr_0,stat_rx_bad_preamble_0,stat_rx_bad_sfd_0,stat_rx_got_signal_os_0,stat_rx_test_pattern_mismatch_0,stat_rx_truncated_0,stat_rx_local_fault_0,stat_rx_remote_fault_0,stat_rx_internal_local_fault_0,stat_rx_received_local_fault_0,stat_rx_status_0,tx_reset_0,user_tx_reset_0,tx_axis_tready_0,tx_axis_tvalid_0,tx_axis_tdata_0[63:0],tx_axis_tlast_0,tx_axis_tkeep_0[7:0],tx_axis_tuser_0,tx_unfout_0,tx_preamblein_0[55:0],ctl_tx_test_pattern_0,ctl_tx_test_pattern_enable_0,ctl_tx_test_pattern_select_0,ctl_tx_data_pattern_select_0,ctl_tx_test_pattern_seed_a_0[57:0],ctl_tx_test_pattern_seed_b_0[57:0],ctl_tx_enable_0,ctl_tx_fcs_ins_enable_0,ctl_tx_ipg_value_0[3:0],ctl_tx_send_lfi_0,ctl_tx_send_rfi_0,ctl_tx_send_idle_0,ctl_tx_custom_preamble_enable_0,ctl_tx_ignore_fcs_0,stat_tx_total_packets_0,stat_tx_total_bytes_0[3:0],stat_tx_total_good_packets_0,stat_tx_total_good_bytes_0[13:0],stat_tx_packet_64_bytes_0,stat_tx_packet_65_127_bytes_0,stat_tx_packet_128_255_bytes_0,stat_tx_packet_256_511_bytes_0,stat_tx_packet_512_1023_bytes_0,stat_tx_packet_1024_1518_bytes_0,stat_tx_packet_1519_1522_bytes_0,stat_tx_packet_1523_1548_bytes_0,stat_tx_packet_small_0,stat_tx_packet_large_0,stat_tx_packet_1549_2047_bytes_0,stat_tx_packet_2048_4095_bytes_0,stat_tx_packet_4096_8191_bytes_0,stat_tx_packet_8192_9215_bytes_0,stat_tx_unicast_0,stat_tx_multicast_0,stat_tx_broadcast_0,stat_tx_vlan_0,stat_tx_bad_fcs_0,stat_tx_frame_error_0,stat_tx_local_fault_0,gt_dmonitorout_0[16:0],gt_eyescandataerror_0[0:0],gt_eyescanreset_0[0:0],gt_eyescantrigger_0[0:0],gt_pcsrsvdin_0[15:0],gt_rxbufreset_0[0:0],gt_rxbufstatus_0[2:0],gt_rxcdrhold_0[0:0],gt_rxcommadeten_0[0:0],gt_rxdfeagchold_0[0:0],gt_rxdfelpmreset_0[0:0],gt_rxlatclk_0[0:0],gt_rxlpmen_0[0:0],gt_rxpcsreset_0[0:0],gt_rxpmareset_0[0:0],gt_rxpolarity_0[0:0],gt_rxprbscntreset_0[0:0],gt_rxprbserr_0[0:0],gt_rxprbssel_0[3:0],gt_rxrate_0[2:0],gt_rxslide_in_0[0:0],gt_rxstartofseq_0[1:0],gt_txbufstatus_0[1:0],gt_txinhibit_0[0:0],gt_txlatclk_0[0:0],gt_txmaincursor_0[6:0],gt_txpcsreset_0[0:0],gt_txpmareset_0[0:0],gt_txpolarity_0[0:0],gt_txpostcursor_0[4:0],gt_txprbsforceerr_0[0:0],gt_txprbssel_0[3:0],gt_txprecursor_0[4:0],gt_txdiffctrl_0[4:0],gt_drpdo_0[15:0],gt_drprdy_0[0:0],gt_drpen_0[0:0],gt_drpwe_0[0:0],gt_drpaddr_0[9:0],gt_drpdi_0[15:0],gt_drpclk_0,gtwiz_reset_tx_datapath_0,gtwiz_reset_rx_datapath_0,gtpowergood_out_0,txoutclksel_in_0[2:0],rxoutclksel_in_0[2:0],tx_clk_out_1,rx_core_clk_1,rx_clk_out_1,gt_loopback_in_1[2:0],rx_reset_1,user_rx_reset_1,rxrecclkout_1,rx_axis_tvalid_1,rx_axis_tdata_1[63:0],rx_axis_tlast_1,rx_axis_tkeep_1[7:0],rx_axis_tuser_1,rx_preambleout_1[55:0],ctl_rx_test_pattern_1,ctl_rx_test_pattern_enable_1,ctl_rx_data_pattern_select_1,ctl_rx_enable_1,ctl_rx_delete_fcs_1,ctl_rx_ignore_fcs_1,ctl_rx_max_packet_len_1[14:0],ctl_rx_min_packet_len_1[7:0],ctl_rx_custom_preamble_enable_1,ctl_rx_check_sfd_1,ctl_rx_check_preamble_1,ctl_rx_process_lfi_1,ctl_rx_force_resync_1,stat_rx_block_lock_1,stat_rx_framing_err_valid_1,stat_rx_framing_err_1,stat_rx_hi_ber_1,stat_rx_valid_ctrl_code_1,stat_rx_bad_code_1,stat_rx_total_packets_1[1:0],stat_rx_total_good_packets_1,stat_rx_total_bytes_1[3:0],stat_rx_total_good_bytes_1[13:0],stat_rx_packet_small_1,stat_rx_jabber_1,stat_rx_packet_large_1,stat_rx_oversize_1,stat_rx_undersize_1,stat_rx_toolong_1,stat_rx_fragment_1,stat_rx_packet_64_bytes_1,stat_rx_packet_65_127_bytes_1,stat_rx_packet_128_255_bytes_1,stat_rx_packet_256_511_bytes_1,stat_rx_packet_512_1023_bytes_1,stat_rx_packet_1024_1518_bytes_1,stat_rx_packet_1519_1522_bytes_1,stat_rx_packet_1523_1548_bytes_1,stat_rx_bad_fcs_1[1:0],stat_rx_packet_bad_fcs_1,stat_rx_stomped_fcs_1[1:0],stat_rx_packet_1549_2047_bytes_1,stat_rx_packet_2048_4095_bytes_1,stat_rx_packet_4096_8191_bytes_1,stat_rx_packet_8192_9215_bytes_1,stat_rx_unicast_1,stat_rx_multicast_1,stat_rx_broadcast_1,stat_rx_vlan_1,stat_rx_inrangeerr_1,stat_rx_bad_preamble_1,stat_rx_bad_sfd_1,stat_rx_got_signal_os_1,stat_rx_test_pattern_mismatch_1,stat_rx_truncated_1,stat_rx_local_fault_1,stat_rx_remote_fault_1,stat_rx_internal_local_fault_1,stat_rx_received_local_fault_1,stat_rx_status_1,tx_reset_1,user_tx_reset_1,tx_axis_tready_1,tx_axis_tvalid_1,tx_axis_tdata_1[63:0],tx_axis_tlast_1,tx_axis_tkeep_1[7:0],tx_axis_tuser_1,tx_unfout_1,tx_preamblein_1[55:0],ctl_tx_test_pattern_1,ctl_tx_test_pattern_enable_1,ctl_tx_test_pattern_select_1,ctl_tx_data_pattern_select_1,ctl_tx_test_pattern_seed_a_1[57:0],ctl_tx_test_pattern_seed_b_1[57:0],ctl_tx_enable_1,ctl_tx_fcs_ins_enable_1,ctl_tx_ipg_value_1[3:0],ctl_tx_send_lfi_1,ctl_tx_send_rfi_1,ctl_tx_send_idle_1,ctl_tx_custom_preamble_enable_1,ctl_tx_ignore_fcs_1,stat_tx_total_packets_1,stat_tx_total_bytes_1[3:0],stat_tx_total_good_packets_1,stat_tx_total_good_bytes_1[13:0],stat_tx_packet_64_bytes_1,stat_tx_packet_65_127_bytes_1,stat_tx_packet_128_255_bytes_1,stat_tx_packet_256_511_bytes_1,stat_tx_packet_512_1023_bytes_1,stat_tx_packet_1024_1518_bytes_1,stat_tx_packet_1519_1522_bytes_1,stat_tx_packet_1523_1548_bytes_1,stat_tx_packet_small_1,stat_tx_packet_large_1,stat_tx_packet_1549_2047_bytes_1,stat_tx_packet_2048_4095_bytes_1,stat_tx_packet_4096_8191_bytes_1,stat_tx_packet_8192_9215_bytes_1,stat_tx_unicast_1,stat_tx_multicast_1,stat_tx_broadcast_1,stat_tx_vlan_1,stat_tx_bad_fcs_1,stat_tx_frame_error_1,stat_tx_local_fault_1,gt_dmonitorout_1[16:0],gt_eyescandataerror_1[0:0],gt_eyescanreset_1[0:0],gt_eyescantrigger_1[0:0],gt_pcsrsvdin_1[15:0],gt_rxbufreset_1[0:0],gt_rxbufstatus_1[2:0],gt_rxcdrhold_1[0:0],gt_rxcommadeten_1[0:0],gt_rxdfeagchold_1[0:0],gt_rxdfelpmreset_1[0:0],gt_rxlatclk_1[0:0],gt_rxlpmen_1[0:0],gt_rxpcsreset_1[0:0],gt_rxpmareset_1[0:0],gt_rxpolarity_1[0:0],gt_rxprbscntreset_1[0:0],gt_rxprbserr_1[0:0],gt_rxprbssel_1[3:0],gt_rxrate_1[2:0],gt_rxslide_in_1[0:0],gt_rxstartofseq_1[1:0],gt_txbufstatus_1[1:0],gt_txinhibit_1[0:0],gt_txlatclk_1[0:0],gt_txmaincursor_1[6:0],gt_txpcsreset_1[0:0],gt_txpmareset_1[0:0],gt_txpolarity_1[0:0],gt_txpostcursor_1[4:0],gt_txprbsforceerr_1[0:0],gt_txprbssel_1[3:0],gt_txprecursor_1[4:0],gt_txdiffctrl_1[4:0],gt_drpdo_1[15:0],gt_drprdy_1[0:0],gt_drpen_1[0:0],gt_drpwe_1[0:0],gt_drpaddr_1[9:0],gt_drpdi_1[15:0],gt_drpclk_1,gtwiz_reset_tx_datapath_1,gtwiz_reset_rx_datapath_1,gtpowergood_out_1,txoutclksel_in_1[2:0],rxoutclksel_in_1[2:0],tx_clk_out_2,rx_core_clk_2,rx_clk_out_2,gt_loopback_in_2[2:0],rx_reset_2,user_rx_reset_2,rxrecclkout_2,rx_axis_tvalid_2,rx_axis_tdata_2[63:0],rx_axis_tlast_2,rx_axis_tkeep_2[7:0],rx_axis_tuser_2,rx_preambleout_2[55:0],ctl_rx_test_pattern_2,ctl_rx_test_pattern_enable_2,ctl_rx_data_pattern_select_2,ctl_rx_enable_2,ctl_rx_delete_fcs_2,ctl_rx_ignore_fcs_2,ctl_rx_max_packet_len_2[14:0],ctl_rx_min_packet_len_2[7:0],ctl_rx_custom_preamble_enable_2,ctl_rx_check_sfd_2,ctl_rx_check_preamble_2,ctl_rx_process_lfi_2,ctl_rx_force_resync_2,stat_rx_block_lock_2,stat_rx_framing_err_valid_2,stat_rx_framing_err_2,stat_rx_hi_ber_2,stat_rx_valid_ctrl_code_2,stat_rx_bad_code_2,stat_rx_total_packets_2[1:0],stat_rx_total_good_packets_2,stat_rx_total_bytes_2[3:0],stat_rx_total_good_bytes_2[13:0],stat_rx_packet_small_2,stat_rx_jabber_2,stat_rx_packet_large_2,stat_rx_oversize_2,stat_rx_undersize_2,stat_rx_toolong_2,stat_rx_fragment_2,stat_rx_packet_64_bytes_2,stat_rx_packet_65_127_bytes_2,stat_rx_packet_128_255_bytes_2,stat_rx_packet_256_511_bytes_2,stat_rx_packet_512_1023_bytes_2,stat_rx_packet_1024_1518_bytes_2,stat_rx_packet_1519_1522_bytes_2,stat_rx_packet_1523_1548_bytes_2,stat_rx_bad_fcs_2[1:0],stat_rx_packet_bad_fcs_2,stat_rx_stomped_fcs_2[1:0],stat_rx_packet_1549_2047_bytes_2,stat_rx_packet_2048_4095_bytes_2,stat_rx_packet_4096_8191_bytes_2,stat_rx_packet_8192_9215_bytes_2,stat_rx_unicast_2,stat_rx_multicast_2,stat_rx_broadcast_2,stat_rx_vlan_2,stat_rx_inrangeerr_2,stat_rx_bad_preamble_2,stat_rx_bad_sfd_2,stat_rx_got_signal_os_2,stat_rx_test_pattern_mismatch_2,stat_rx_truncated_2,stat_rx_local_fault_2,stat_rx_remote_fault_2,stat_rx_internal_local_fault_2,stat_rx_received_local_fault_2,stat_rx_status_2,tx_reset_2,user_tx_reset_2,tx_axis_tready_2,tx_axis_tvalid_2,tx_axis_tdata_2[63:0],tx_axis_tlast_2,tx_axis_tkeep_2[7:0],tx_axis_tuser_2,tx_unfout_2,tx_preamblein_2[55:0],ctl_tx_test_pattern_2,ctl_tx_test_pattern_enable_2,ctl_tx_test_pattern_select_2,ctl_tx_data_pattern_select_2,ctl_tx_test_pattern_seed_a_2[57:0],ctl_tx_test_pattern_seed_b_2[57:0],ctl_tx_enable_2,ctl_tx_fcs_ins_enable_2,ctl_tx_ipg_value_2[3:0],ctl_tx_send_lfi_2,ctl_tx_send_rfi_2,ctl_tx_send_idle_2,ctl_tx_custom_preamble_enable_2,ctl_tx_ignore_fcs_2,stat_tx_total_packets_2,stat_tx_total_bytes_2[3:0],stat_tx_total_good_packets_2,stat_tx_total_good_bytes_2[13:0],stat_tx_packet_64_bytes_2,stat_tx_packet_65_127_bytes_2,stat_tx_packet_128_255_bytes_2,stat_tx_packet_256_511_bytes_2,stat_tx_packet_512_1023_bytes_2,stat_tx_packet_1024_1518_bytes_2,stat_tx_packet_1519_1522_bytes_2,stat_tx_packet_1523_1548_bytes_2,stat_tx_packet_small_2,stat_tx_packet_large_2,stat_tx_packet_1549_2047_bytes_2,stat_tx_packet_2048_4095_bytes_2,stat_tx_packet_4096_8191_bytes_2,stat_tx_packet_8192_9215_bytes_2,stat_tx_unicast_2,stat_tx_multicast_2,stat_tx_broadcast_2,stat_tx_vlan_2,stat_tx_bad_fcs_2,stat_tx_frame_error_2,stat_tx_local_fault_2,gt_dmonitorout_2[16:0],gt_eyescandataerror_2[0:0],gt_eyescanreset_2[0:0],gt_eyescantrigger_2[0:0],gt_pcsrsvdin_2[15:0],gt_rxbufreset_2[0:0],gt_rxbufstatus_2[2:0],gt_rxcdrhold_2[0:0],gt_rxcommadeten_2[0:0],gt_rxdfeagchold_2[0:0],gt_rxdfelpmreset_2[0:0],gt_rxlatclk_2[0:0],gt_rxlpmen_2[0:0],gt_rxpcsreset_2[0:0],gt_rxpmareset_2[0:0],gt_rxpolarity_2[0:0],gt_rxprbscntreset_2[0:0],gt_rxprbserr_2[0:0],gt_rxprbssel_2[3:0],gt_rxrate_2[2:0],gt_rxslide_in_2[0:0],gt_rxstartofseq_2[1:0],gt_txbufstatus_2[1:0],gt_txinhibit_2[0:0],gt_txlatclk_2[0:0],gt_txmaincursor_2[6:0],gt_txpcsreset_2[0:0],gt_txpmareset_2[0:0],gt_txpolarity_2[0:0],gt_txpostcursor_2[4:0],gt_txprbsforceerr_2[0:0],gt_txprbssel_2[3:0],gt_txprecursor_2[4:0],gt_txdiffctrl_2[4:0],gt_drpdo_2[15:0],gt_drprdy_2[0:0],gt_drpen_2[0:0],gt_drpwe_2[0:0],gt_drpaddr_2[9:0],gt_drpdi_2[15:0],gt_drpclk_2,gtwiz_reset_tx_datapath_2,gtwiz_reset_rx_datapath_2,gtpowergood_out_2,txoutclksel_in_2[2:0],rxoutclksel_in_2[2:0],tx_clk_out_3,rx_core_clk_3,rx_clk_out_3,gt_loopback_in_3[2:0],rx_reset_3,user_rx_reset_3,rxrecclkout_3,rx_axis_tvalid_3,rx_axis_tdata_3[63:0],rx_axis_tlast_3,rx_axis_tkeep_3[7:0],rx_axis_tuser_3,rx_preambleout_3[55:0],ctl_rx_test_pattern_3,ctl_rx_test_pattern_enable_3,ctl_rx_data_pattern_select_3,ctl_rx_enable_3,ctl_rx_delete_fcs_3,ctl_rx_ignore_fcs_3,ctl_rx_max_packet_len_3[14:0],ctl_rx_min_packet_len_3[7:0],ctl_rx_custom_preamble_enable_3,ctl_rx_check_sfd_3,ctl_rx_check_preamble_3,ctl_rx_process_lfi_3,ctl_rx_force_resync_3,stat_rx_block_lock_3,stat_rx_framing_err_valid_3,stat_rx_framing_err_3,stat_rx_hi_ber_3,stat_rx_valid_ctrl_code_3,stat_rx_bad_code_3,stat_rx_total_packets_3[1:0],stat_rx_total_good_packets_3,stat_rx_total_bytes_3[3:0],stat_rx_total_good_bytes_3[13:0],stat_rx_packet_small_3,stat_rx_jabber_3,stat_rx_packet_large_3,stat_rx_oversize_3,stat_rx_undersize_3,stat_rx_toolong_3,stat_rx_fragment_3,stat_rx_packet_64_bytes_3,stat_rx_packet_65_127_bytes_3,stat_rx_packet_128_255_bytes_3,stat_rx_packet_256_511_bytes_3,stat_rx_packet_512_1023_bytes_3,stat_rx_packet_1024_1518_bytes_3,stat_rx_packet_1519_1522_bytes_3,stat_rx_packet_1523_1548_bytes_3,stat_rx_bad_fcs_3[1:0],stat_rx_packet_bad_fcs_3,stat_rx_stomped_fcs_3[1:0],stat_rx_packet_1549_2047_bytes_3,stat_rx_packet_2048_4095_bytes_3,stat_rx_packet_4096_8191_bytes_3,stat_rx_packet_8192_9215_bytes_3,stat_rx_unicast_3,stat_rx_multicast_3,stat_rx_broadcast_3,stat_rx_vlan_3,stat_rx_inrangeerr_3,stat_rx_bad_preamble_3,stat_rx_bad_sfd_3,stat_rx_got_signal_os_3,stat_rx_test_pattern_mismatch_3,stat_rx_truncated_3,stat_rx_local_fault_3,stat_rx_remote_fault_3,stat_rx_internal_local_fault_3,stat_rx_received_local_fault_3,stat_rx_status_3,tx_reset_3,user_tx_reset_3,tx_axis_tready_3,tx_axis_tvalid_3,tx_axis_tdata_3[63:0],tx_axis_tlast_3,tx_axis_tkeep_3[7:0],tx_axis_tuser_3,tx_unfout_3,tx_preamblein_3[55:0],ctl_tx_test_pattern_3,ctl_tx_test_pattern_enable_3,ctl_tx_test_pattern_select_3,ctl_tx_data_pattern_select_3,ctl_tx_test_pattern_seed_a_3[57:0],ctl_tx_test_pattern_seed_b_3[57:0],ctl_tx_enable_3,ctl_tx_fcs_ins_enable_3,ctl_tx_ipg_value_3[3:0],ctl_tx_send_lfi_3,ctl_tx_send_rfi_3,ctl_tx_send_idle_3,ctl_tx_custom_preamble_enable_3,ctl_tx_ignore_fcs_3,stat_tx_total_packets_3,stat_tx_total_bytes_3[3:0],stat_tx_total_good_packets_3,stat_tx_total_good_bytes_3[13:0],stat_tx_packet_64_bytes_3,stat_tx_packet_65_127_bytes_3,stat_tx_packet_128_255_bytes_3,stat_tx_packet_256_511_bytes_3,stat_tx_packet_512_1023_bytes_3,stat_tx_packet_1024_1518_bytes_3,stat_tx_packet_1519_1522_bytes_3,stat_tx_packet_1523_1548_bytes_3,stat_tx_packet_small_3,stat_tx_packet_large_3,stat_tx_packet_1549_2047_bytes_3,stat_tx_packet_2048_4095_bytes_3,stat_tx_packet_4096_8191_bytes_3,stat_tx_packet_8192_9215_bytes_3,stat_tx_unicast_3,stat_tx_multicast_3,stat_tx_broadcast_3,stat_tx_vlan_3,stat_tx_bad_fcs_3,stat_tx_frame_error_3,stat_tx_local_fault_3,gt_dmonitorout_3[16:0],gt_eyescandataerror_3[0:0],gt_eyescanreset_3[0:0],gt_eyescantrigger_3[0:0],gt_pcsrsvdin_3[15:0],gt_rxbufreset_3[0:0],gt_rxbufstatus_3[2:0],gt_rxcdrhold_3[0:0],gt_rxcommadeten_3[0:0],gt_rxdfeagchold_3[0:0],gt_rxdfelpmreset_3[0:0],gt_rxlatclk_3[0:0],gt_rxlpmen_3[0:0],gt_rxpcsreset_3[0:0],gt_rxpmareset_3[0:0],gt_rxpolarity_3[0:0],gt_rxprbscntreset_3[0:0],gt_rxprbserr_3[0:0],gt_rxprbssel_3[3:0],gt_rxrate_3[2:0],gt_rxslide_in_3[0:0],gt_rxstartofseq_3[1:0],gt_txbufstatus_3[1:0],gt_txinhibit_3[0:0],gt_txlatclk_3[0:0],gt_txmaincursor_3[6:0],gt_txpcsreset_3[0:0],gt_txpmareset_3[0:0],gt_txpolarity_3[0:0],gt_txpostcursor_3[4:0],gt_txprbsforceerr_3[0:0],gt_txprbssel_3[3:0],gt_txprecursor_3[4:0],gt_txdiffctrl_3[4:0],gt_drpdo_3[15:0],gt_drprdy_3[0:0],gt_drpen_3[0:0],gt_drpwe_3[0:0],gt_drpaddr_3[9:0],gt_drpdi_3[15:0],gt_drpclk_3,gtwiz_reset_tx_datapath_3,gtwiz_reset_rx_datapath_3,gtpowergood_out_3,txoutclksel_in_3[2:0],rxoutclksel_in_3[2:0],gt_refclk_p[0:0],gt_refclk_n[0:0],gt_refclk_out[0:0],sys_reset,dclk";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "xxv_ethernet_v3_0_0,Vivado 2019.1";
begin
end;
